source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Bitpod_Example', :exclusive => true do
  pod "Bitpod", :path => "../"
end

target 'Bitpod_Tests', :exclusive => true do
  pod "Bitpod", :path => "../"

  
end
